#!/bin/bash
set -o errexit

DOMAIN=${1:-magento2.local}
VERSION=${2:-2.4.3}
EDITION=${3:-community}

curl -s https://raw.githubusercontent.com/markshust/docker-magento/master/lib/template | bash

# &&'s are used below otherwise onelinesetup script fails/errors on bin/download
bin/download "${VERSION}" "${EDITION}" \
  && echo "Your system password has been requested to add an entry to /etc/hosts..." \
  && echo "127.0.0.1 ::1 $DOMAIN" | sudo tee -a /etc/hosts \
  && bin/setup $DOMAIN
  
# add cron scheduler in base
bin/composer require mageplaza/module-cron-schedule
bin/magento setup:upgrade
bin/magento setup:static-content:deploy

#Disable two-factor for dev environments
bin/magento module:disable Magento_TwoFactorAuth
bin/magento cache:flush
